spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost/myblog?characterEncoding=utf8&serverTimezone=GMT%2B8&useSSl=true
    username: root
    password: 430423
  servlet:
    multipart:
      max-request-size: 200MB
      max-file-size: 100MB

mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  file:
    name: mylog.txt
